services:
  - type: web
    name: field-uploads
    env: python
    plan: free

    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 2 -k gthread -b 0.0.0.0:$PORT server:app"
    autoDeploy: true

    envVars:
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: DATA_DIR
        value: "/opt/render/project/src/data"
